ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER report_excel_user IDENTIFIED BY report_excel
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO report_excel_user;

EXIT;